- Makefile
- README.md
- rampwf/utils/command_line.py
- rampwf/utils/testing.py
- rampwf/utils/tests/test_command_line.py
- rampwf/utils/tests/test_testing.py
`"*"` can be provided and all the submissions can be tested. We can also provide a list.
> [MRG] EHN possibility to test several submission

- rampwf/kits/ramp_kit.py
- rampwf/score_types/__init__.py
- rampwf/score_types/brier_score.py
- rampwf/utils/testing.py
- rampwf/workflows/__init__.py
- rampwf/workflows/grid_feature_extractor.py
- rampwf/workflows/grid_feature_extractor_classifier.py
I have added Brier Score scoring options and a gridded feature extractor for processing netCDF files with xarray that contain multiple ensemble members.
> Score and feature extraction additions for California Rainfall hackathon

- rampwf/score_types/__init__.py
- rampwf/score_types/soft_accuracy.py
- rampwf/score_types/tests/test_soft_accuracy.py
I need a rapid review on this.
Travis is down due to the scipy problem, but pytest runs fine on my computer.
> adding soft accuracy score

- rampwf/score_types/__init__.py
- rampwf/score_types/normalized_gini.py
- rampwf/utils/testing.py
I also need a rapid review on this.
> adding normalized Gini index and outputting y_pred_test optionally

- README.md
IMO a huge README where scrolling gets you lost is not very attractive.
Also a lot of it were specific examples from titanic.
Please comment..
> [WIP] README refactoring after wiki creation

- rampwf/kits/ramp_kit.py
- rampwf/prediction_types/base.py
- rampwf/utils/__init__.py
- rampwf/utils/combine.py
- rampwf/utils/command_line.py
- rampwf/utils/testing.py
- rampwf/utils/tests/test_testing.py
- requirements.txt
- testing-requirements.txt
Not much code but will need careful review. Make it more pythonesque.
> porting cv bagging from ramp-board to ramp-workflow

- rampwf/utils/tests/test_testing.py
This just makes reporting a bit nicer (one test per kit)
> TST: parametrize starting kit submission tests

- rampwf/prediction_types/detection.py
- rampwf/prediction_types/tests/test_detection_predictions.py
- rampwf/score_types/tests/test_detection.py
> BUG: detection predictions - fix blending when no overlap between different sets

- rampwf/utils/submission.py
This is needed for ramp-backend to save the durations in the db.
See https://github.com/paris-saclay-cds/ramp-backend/issues/6
> Save train, valid and test durations in ramp_test_submission

- rampwf/score_types/__init__.py
- rampwf/score_types/normalized_rmse.py
- rampwf/tests/kits/boston_housing/problem.py
Adding a regression score that normalizes the RMSE wrt the std of y_true.
> normalized rmse

- rampwf/tests/kits/drug_spectra/submissions/starting_kit/classifier.py
Fixes https://github.com/paris-saclay-cds/ramp-workflow/issues/152
@kegl
> Drug spectra test kit: set low n_components of PCA

- rampwf/utils/command_line.py
- rampwf/utils/tests/test_command_line.py
- setup.py
Add a simple command line "ramp_leaderboard" (https://github.com/mehdidc/ramp-leaderboard) to display a leaderboard of local submissions.
(see #132)
Continuation of #133 using my fork for the source branch
> Ramp leaderboard

- rampwf/tests/kits/titanic/titanic_starting_kit.ipynb
- rampwf/tests/kits/titanic_no_test/titanic_no_test_starting_kit.ipynb
- rampwf/utils/cli/show.py
- rampwf/utils/cli/testing.py
- rampwf/utils/command_line.py
- setup.py
> MAINT: refactor the CLI using click

- requirements.txt
- setup.py
Closes https://github.com/paris-saclay-cds/ramp-workflow/issues/179
> Add click to install requires

- .circleci/config.yml
Improve circle CI config and set to build doc and push to website repo when master changes.
> [MRG] [DOC] Improve circleci config

- rampwf/tests/kits/titanic/submissions/starting_kit/classifier.py
- rampwf/tests/kits/titanic/titanic_starting_kit.ipynb
- rampwf/tests/kits/titanic_no_test/submissions/starting_kit/classifier.py
- rampwf/tests/kits/titanic_no_test/titanic_no_test_starting_kit.ipynb
> [MRG] Fixes titanic kit error

- .travis.yml
- testing-requirements.txt
> FIX failing test

- rampwf/utils/cli/testing.py
Add option to ignore warning when running `ramp test`
It is useful for: https://github.com/paris-saclay-cds/ramp-board/pull/362
> ENH add option to ignore warnings

- rampwf/externals/tabulate.py
- rampwf/hyperopt/hyperopt.py
- rampwf/utils/__init__.py
- rampwf/utils/importing.py
- rampwf/utils/submission.py
- rampwf/utils/testing.py
- rampwf/workflows/classifier.py
- rampwf/workflows/clusterer.py
- rampwf/workflows/feature_extractor.py
- rampwf/workflows/grid_feature_extractor.py
- rampwf/workflows/image_classifier.py
- rampwf/workflows/object_detector.py
- rampwf/workflows/regressor.py
- rampwf/workflows/simplified_image_classifier.py
- rampwf/workflows/ts_feature_extractor.py
closes #204 
Remove `DeprecationWarning` due to imp and `collections.abc`
Updating `tabulate` in this regard.
> MNT remove deprecation warning due to our code

- rampwf/utils/io.py
> BUG fix trace saving

- rampwf/utils/submission.py
- rampwf/workflows/sklearn_pipeline.py
I just saw that we were raising some warning when dealing with pandas dataframe that should not happen. It was not coming from the notebooks from some of the line that I modified.
I also edited the new pipeline to use `_safe_indexing` and have naming closer to the scikit-learn convention.
> FIX couple of style fix + copy issue with dataframe

- rampwf/workflows/sklearn_pipeline.py
Just add some documentation and just rename some of the variable to be more inline with the code.
> MNT/DOC add documentation for scikit-learn wrapper

- doc/command_line.rst
- doc/problem.rst
- doc/workflow.rst
- Use click for command line documentation
- Add doc for the new Estimator and EstimatorExternalData workflows
> DOC use click for command line & add estimator workflow

- rampwf/utils/importing.py
- rampwf/utils/sanitize.py
- rampwf/utils/tests/test_sanitize.py
- rampwf/workflows/classifier.py
- rampwf/workflows/clusterer.py
- rampwf/workflows/feature_extractor.py
- rampwf/workflows/grid_feature_extractor.py
- rampwf/workflows/image_classifier.py
- rampwf/workflows/object_detector.py
- rampwf/workflows/regressor.py
- rampwf/workflows/simplified_image_classifier.py
- rampwf/workflows/sklearn_pipeline.py
- rampwf/workflows/ts_feature_extractor.py
Adds very light input sanitizing of user submissions to make aware that poking around the RAMP server is not recommended.
For sensitive discussions please use email.
The actual long term solution is https://github.com/paris-saclay-cds/ramp-board/pull/374 but it's still useful to detect attempts and make users aware I think. Docker is not completely fullproof either https://resources.whitesourcesoftware.com/blog-whitesource/top-5-docker-vulnerabilities
> Sanitize user input in workflows

- README.rst
> Put the doc url in the readme

- rampwf/score_types/soft_accuracy.py
> Remove redundnacy in soft accuracy

- ci_tools/circle/push_doc.sh
Adds a condition in `push_doc.sh` to build and publish the doc of the `advanced` branch
> DOC Add condition to build doc for advanced branch

- rampwf/hyperopt/hyperopt.py
- rampwf/hyperopt/tests/interfaces/header_in_files/titanic/submissions/one_hyper_kit/classifier.py
- rampwf/hyperopt/tests/interfaces/header_in_files/titanic/submissions/one_hyper_kit/feature_extractor.py
- rampwf/hyperopt/tests/test_hyperparameter.py
> Advanced hyperopt

- rampwf/score_types/__init__.py
Exposing  ClassifierBaseScoreType so kits can use it.
> Add ClassifierBaseScoreType to score_types.__init__

- rampwf/score_types/negative_log_likelihood.py
- rampwf/utils/combine.py
See:
https://lgtm.com/projects/g/paris-saclay-cds/ramp-workflow/?severity=recommendation
> Fix LGTM.com recommendations

- rampwf/tests/kits/drug_spectra/problem.py
Fixes a flake8 issue introduced in https://github.com/paris-saclay-cds/ramp-workflow/pull/289#issuecomment-973052538
> MAINT Fix a flake8 issue

- rampwf/utils/testing.py
> fix csv naming in ramp_blend_submissions
