paris-saclay-cds/ramp-workflow

setup.py
No need to use `setup` from numpy.distutils instead of just from setuptools
=> remove usage of numpy.distutils

.travis.yml, install_requirements.sh, rampwf/kits/ramp_kit.py, rampwf/utils/testing.py, rampwf/workflows/image_classifier.py, requirements.txt, setup.py, testing-requirements.txt
This PR intends to clean up the dependency tree of ramp_workflow.
The idea is to trim off all dependencies related to a particular ramp-kit.
The ramp-kits will therefore need to have a specific requirement.txt file listing the dependencies, which will be installed then using pip or conda.
=> Making ramp_workflow pip installable

rampwf/utils/testing.py
Currently, when `ramp_test_submission` is used, scores are printed on different subsets of the data for each CV fold. These are somewhat difficult to parse, particularly if the number of scores becomes large (thinking `mars_craters`).
For instance, for `california_rainfall` we will get,
```
CV fold 0
train BSS = -1.489
valid BSS = -2.388
test BSS = -1.386
train BS = 0.244
valid BS = 0.246
test BS = 0.242
train BS Rel = 0.018
valid BS Rel = 0.014
test BS Rel = 0.023
train BS Res = 0.073
valid BS Res = 0.115
test BS Res = 0.111
train AUC = 0.712
valid AUC = 0.806
test AUC = 0.773
```
This PR uses pandas to pretty print a table of scores instead. The previous example would thus produce,
```
CV fold 0
score    AUC     BS  BS Rel  BS Res    BSS
step
train  0.712  0.244   0.018   0.073 -1.489 …
```
=> Pretty print CV scores

rampwf/utils/importing.py, rampwf/workflows/classifier.py, rampwf/workflows/clusterer.py, rampwf/workflows/feature_extractor.py, rampwf/workflows/grid_feature_extractor.py, rampwf/workflows/image_classifier.py, rampwf/workflows/object_detector.py, rampwf/workflows/regressor.py, rampwf/workflows/simplified_image_classifier.py, rampwf/workflows/ts_feature_extractor.py
And at the same time made it into a utility function to avoid repeated code.
This allows to do a `feature_extractor.py` with something like:
```
from joblib import Memory
memory = Memory(cachedir='./cache', verbose=1)
class FeatureExtractor():
def __init__(self):
pass
def fit(self, X_df, y):
pass
def transform(self, X_df):
return _transform(X_df)
@memory.cache
def _transform(X_df):
...
computationaly expensive feature extraction
...
return X_df_transformed
```
The above already works, but then if you have multiple submissions with a different transform method (but same name), they would each time overwrite each other cached results. This patch solves that, and is in general also a good clean-up IMO.
=> Update import source name to allow caching multiple submissions

rampwf/score_types/__init__.py
Exposing the class `BaseScoreType` for the use case : reimplementing / customizing a scoring metric.
=> expose the class BaseScoreType

rampwf/prediction_types/detection.py, rampwf/prediction_types/tests/test_detection_predictions.py
Ugly hack, but I think should solve the problem. 
Ideally predictions with zero confidence are discarded in an earlier step, but I think  it is rather costly the go through all predictions just to do that.
=> BUG: blending detection predictions with zero confidence

rampwf/utils/importing.py
Runtime warnings have appeared recently when running the `ramp_test_submission` looking like
```bash
./submissions/starting_kit/feature_extractor.py:2: RuntimeWarning: Parent module '.submissions.starting_kit' not found while handling absolute import
import numpy as np
```
This is quite annoying to find these warnings in the prompt so I just filtered them in this PR.
We might need to find out why these warnings have appeared..
=> Suppress Runtime Warnings when importing from starting kits

rampwf/utils/testing.py
Save the scores of each fold into a csv. I would find that useful when experimenting  with ramp_test_submission locally. Like I am thinking to have a minimal tool that displays the leaderboard based on all submissions in submission/.
=> save fold scores

rampwf/utils/command_line.py
The fancy new local `ramp_leaderboard` uses tabulate that doesn't work on windows. We'll catch the exception and revert to pandas rendering the table.
=> lazy import tabulate

.travis.yml, rampwf/tests/test_kits.py, rampwf/utils/command_line.py, rampwf/utils/testing.py, rampwf/utils/tests/test_command_line.py
This PR allows to pass a new parameter `ramp_submission_dir` to specify a a directory where the submissions are stored. This is useful when dealing with the backend server.
=> [MRG] EHN: add submission path when to train a submission

rampwf/utils/pretty_print.py, rampwf/utils/scoring.py, rampwf/utils/submission.py, rampwf/utils/testing.py
Score matrix was reordered when doing `unstack()` so precisions specified in `problem.score_types` were applied in the wrong order before printing. I added an explicit `reorder_df_scores` which is called before rounding and printing. In addition, I did some naming cosmetics in `bag_submissions` (ie `score_types` instead of `score_type` and `score_type` instead of `score`) to be consistent.
=> Score reorder bug

rampwf/tests/test_kits.py, rampwf/utils/command_line.py, rampwf/utils/io.py, rampwf/utils/submission.py, rampwf/utils/testing.py
To unify local and remote training, we'll save everything that we need in the DB into files in `submissions/<submission>/training_output/fold_<i>`, including the state. After rsync, the script can check the file `state.txt` (in each fold), and act accordingly. If the state is `training_error`, `validation_error`, or `test_error`, `submissions/<submission>/training_output/fold_<i>/error.txt` will contain part of the stack that corresponds to the user submission.
=> saving state and error, not only y_pred

.circleci/config.yml, .gitignore, doc/Makefile, doc/command_line.rst, doc/conf.py, doc/contribute.rst, doc/data.rst, doc/index.rst, doc/make.bat, doc/problem.rst, doc/scoring.rst, doc/using_kits.rst, doc/who_are_you.rst, doc/workflow.rst, requirements.txt
Update documentation and move from wiki to sphinx documentation.
=> [MRG] [DOC] Add sphinx documentation

doc/index.rst
Updating the doc and avoid to mention `git+` when installing via `pip`
=> DOC update to mention PyPI installed

requirements.txt, setup.py
`_safe_indexing` became private in `scikit-learn` 0.22 so we need at least this version.
I think that we should synchronize with the latest scikit-learn version anyway.
=> MNT update the minium version of scikit-learn

rampwf/utils/pretty_print.py, rampwf/utils/scoring.py, testing-requirements.txt
closes #157 
It is annoying when using a windows command prompt.
=> MNT stop using colored in Windows since it does not work

rampwf/utils/command_line.py
Fix lint which was causing CIs to fail:
> rampwf/utils/command_line.py:413:21: F523 '...'.format(...) has unused arguments at position(s): 1
rampwf/utils/command_line.py:439:21: F523 '...'.format(...) has unused arguments at position(s): 1
The command "flake8 rampwf --ignore=F401,E211,E265,W503,W504 --exclude rampwf/externals" exited with 1.
=> Fix error message in _filter_and_sort_leaderboard_df

rampwf/utils/submission.py, rampwf/utils/tests/test_submission.py
Pickling was working but raising a non related warning because the file was not read as a binary file. An error should have been raised instead of a warning saying that the model cannot be pickled.
The pickled file is now read as a binary file and only Pickle errors are caught by the try except clause.
PS: this is also fixing two non related flake8 errors to make Travis happy
=> Improve pickle

doc/data.rst, doc/using_kits.rst, doc/workflow.rst
Update documentation to instruct that `prepare_data.py` does not copy the public data files to the 'ramp-kits' directory. This should be done on the server to be robust to different server file configurations.
Made some clarifications as well.
cc @glemaitre @agramfort
=> DOC Update prepare_data instructions

testing-requirements.txt
Fixes #239 
Specifies keras version in `testing-requirements.txt` for compatibility with current tensorflow version.
=> [MRG] Fix CI with keras version

rampwf/tests/test_kits.py, rampwf/utils/importing.py
=> [MRG] Imports and cloudpickle

rampwf/utils/pretty_print.py
Is there a reason why we print score with a fixed width of 160 [here]( https://github.com/paris-saclay-cds/ramp-workflow/blob/master/rampwf/utils/pretty_print.py#L57 ) ?
Setting `display.width` to 0 would allow pandas to autodetects the size of terminal window, avoiding useless shortening in the printed scores
=> Setting display.width to None

rampwf/utils/notebook.py
Appveyor is red now that nbconvert is installed with a version higher than 6. It was green when using a version < 6.
Trying to fix it by forcing utf8 encoding when reading the notebook. Note that the notebook is written to a file with an utf8 encoding (https://github.com/paris-saclay-cds/ramp-workflow/blob/master/rampwf/utils/notebook.py#L59)
=> FIX encoding for new nbconvert version

ci_tools/circle/build_doc.sh
scikit-learn cannot be installed yet with python 3.9, this is making circle fail, see [comment](https://github.com/paris-saclay-cds/ramp-workflow/pull/257#issuecomment-734286148) in PR #257.
=> CI Force python 3.8

doc/command_line.rst, rampwf/utils/cli/testing.py, rampwf/utils/cli/tests/test_cli.py
If this can be useful to anyone I am sharing this here.
This was done following [click documentation](https://click.palletsprojects.com/en/7.x/bashcomplete/#shell-completion).
As written in the [documentation](https://click.palletsprojects.com/en/7.x/bashcomplete/#activation) I need to activate the autocompletion for my shell for this to work.
=> Autocompletion for submission names

.pre-commit-config.yaml, .travis.yml, Makefile, doc/conf.py, doc/contribute.rst, setup.cfg
- Simplify flake8 usage by putting all relevant config in a `setup.cfg` file
- add a documentation section on code style under contributing
- add a minimal [pre-commit](https://pre-commit.com/) to make it more  convenient to run linters before each commit (use is optional)
=> MAINT Add pre-commit, simplify flake8 setup

CHANGELOG.md
Updates changelog in preparation for 0.4.0 release (#264) 
I haven't done the changelog for all previous versions, just indicated that they were there. Also there is a bit of the confusion in that there was a v0.2.0 git tag in 2017 then a 0.2.0 release in 2020.
=> DOC Update changelog for 0.4.0

testing-requirements.txt
Fixes Github security warnings on the home page (and in email reminders). Tensorflow can probably be updated to a later version as well but I'm not fully sure about the implications and for now I just want to remove the warnings.
=> MAINT/Fix security vulnerability warning by updating to tensorflow 2.0.4

doc/whats_new.rst, rampwf/utils/cli/testing.py
A last small fix from advanced (https://github.com/paris-saclay-cds/ramp-workflow/pull/246) which correctly takes into account the `--ramp-submission-dir` parameter in ramp-test when `--submission=ALL`
=> CLI Fix --ramp-submission-dir parameter in ramp-test

ci_tools/circle/build_doc.sh
Fixing circle CI by using sphinx with a version lower than 4.0
Closes #278
=> Force sphinx to have version lower than 4.0

doc/problem.rst, doc/whats_new.rst, rampwf/tests/test_kits.py, rampwf/utils/testing.py
Closes #181
With this PR merged, users would be able to import packages copied to external_imports directory.
This PR adds the external_imports directory to sys.path.
Let's imagine this kit structure:
problem.py
data/
external_imports/
......utils/
............test_imports.py
Then to import test_imports.py, it is sufficient to do (from inside problem.py or estimator/classifier.py):
from utils import test_imports
=> ENH add the external_imports directory to sys.path

rampwf/score_types/__init__.py, rampwf/utils/testing.py
Porting the blending code to decoupled cv.
=> Fix blending decoupled cv

rampwf/prediction_types/combined.py
The value assigned to local variable `n_columns` is never used.
=> Unused local variable

rampwf/hyperopt/hyperopt.py, rampwf/score_types/brier_score.py, rampwf/score_types/roc_auc.py, rampwf/tests/kits/digits/submissions/starting_kit/batch_classifier.py, rampwf/workflows/clusterer.py
Not sure about `joined back the the` → `joined back to the` here:
> This function returns a vector of labels (cluster assignments) which is then joined back the the event id column and returned (to be passed into `prediction_types.Clustering` and evaluated by `score_types.clustering_efficiency`).
=> Fix typos (repeated words)

rampwf/utils/sanitize.py, rampwf/utils/tests/test_sanitize.py
For some challenges, users need to load images with Image.open
from the PIL library. This is not possible as _sanitize_input
is too restrictive. This commits intend to change this.
=> ENH allow open in user code for non-os moudles

.bumpversion.cfg, doc/whats_new.rst, rampwf/_version.py
Closes https://github.com/paris-saclay-cds/ramp-workflow/issues/300
I can confirm that this version will work with ramp-board CI.
=> Release version 0.5.0
